
spring:

  application:
    name: my-wms

  jackson:
    time-zone: UTC

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my-wms
    username: postgres
    password: totvs@123
    
  flyway:
    enabled: false
    migrate: true
    locations: classpath:db/migration
    schemas: public
    baselineOnMigrate: true
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:      
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # https://github.com/spring-projects/spring-boot/issues/12007
        hbm2ddl:
          auto: "none"
        show_sql: true
        format_sql: true

  cloud:
    stream:
      defaultBinder: rabbit1
      bindings:
       wms-input-events:       
         destination: my-wms-exchange
         group: my-wms 
         binder: rabbit1
       wms-output-events:
         destination: my-wms-exchange
         binder: rabbit1
       tjf-messaging-error-input:
         destination: my-wms-errors
         group: my-wms-errors
         binder: rabbit1
       tjf-messaging-error-output:
         destination: my-wms-errors
         group: my-wms-errors
         binder: rabbit1
         producer:
           requiredGroups: my-wms-errors
      rabbit:
         bindings:
           rac-input:
             consumer:
               exchange-Type: fanout   
      binders:
        rabbit1:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtualHost: /
        rabbit2:
          type: rabbit
          defaultCandidate: false
          inheritEnvironment: false
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtualHost: /

server:
  port: 7170
 